### ISSUE TITLE
lineageot.fit_tree not working

### ISSUE THREAD

**Issue by ShouWenWang** [aforr/LineageOT-demo#1]
Hi, Aden
       I want to try your method on my own lineage tracing data. However, the first step **lineageot.fit_tree** is not working.  Specifically, the step **inf.neighbor_join(lineage_distances)** returns an empty graph. This is a clonal data without nesting structure (static barcoding). I wonder if you have any thoughts on this. And looking forward to your help!

To reproduce this behavior, you can download the adata object here:
https://www.dropbox.com/s/nqbtq752mx9gn1g/bifurcation_data_for_lineage_ot.h5ad?dl=0

Then, loading this data as adata_orig, you can run:

import lineageot.inference as inf

time=2
adata=adata_orig[adata_orig.obs['time'] == time]
barcodes_key='barcodes'

# compute distances
barcode_length = adata.obsm[barcodes_key].shape[1]
# last row is (unobserved) root of the tree
lineage_distances = inf.barcode_distances(np.concatenate([adata.obsm[barcodes_key], np.zeros([1,barcode_length])]))

# compute tree
fitted_tree = inf.neighbor_join(lineage_distances)

# annotate tree with node times
inf.add_leaf_barcodes(fitted_tree, adata.obsm[barcodes_key])
inf.add_leaf_times(fitted_tree, time)

# Estimating a uniform mutation rate for all target sites
rate_estimate = inf.rate_estimator(adata.obsm[barcodes_key], time)
inf.annotate_tree(fitted_tree, 
                  rate_estimate*np.ones(barcode_length),
                  time_inference_method = 'least_squares');

**Comment by ShouWenWang** [comment]
Sorry, it seems to be working.  The error might be related to something else. I will try to figure that out myself.

**Comment by aforr** [comment]
Hi Shou-Wen,

Hope you sort out whatever the issue is. Let me know if you run into any problems I can help with. I'd be very curious to see your results with clonal data whenever they're ready.
