### ISSUE TITLE
KeyError : 'barcodes' with lineageot.fit_tree

### ISSUE THREAD

**Issue by nadinegheziel** [aforr/LineageOT-demo#2]
**Hi ! 

I'm trying to run the Lineage OT notebook on my own data but I am having trouble with the lineageot.fit_tree function **

I have succesfully run WOT on the same data so I guess it should be working here too but I would accept any help !

** First code : Creation of the input with WOT pipeline :** 

import ipywidgets as widgets
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import wot

CELL_DAYS_PATH = './cell_days.txt'
FLE_COORDS_PATH ='./coord.txt'

coord_df = pd.read_csv(FLE_COORDS_PATH, index_col='id', sep='\t')
days_df = pd.read_csv(CELL_DAYS_PATH, index_col='id', sep='\t')
# Read expression matrix, cell days, and 2-d coordinates
adata = wot.io.read_dataset('./aggr_J0_J1_J4.h5ad', obs=[days_df,coord_df])
print("done")
unique_days = adata.obs['day'].unique()
unique_days = unique_days[np.isnan(unique_days) == False]
adata.annData.write(filename='anndata_object.h5ad')

**Second code : Running LineageOT on the matrix :**

import anndata
import lineageot
import numpy as np

adata = anndata.read_h5ad("anndata_object.h5ad")

lineage_tree_4 = lineageot.fit_tree(adata[adata.obs['origin_cell'] == 4], 4, barcodes_key = "barcodes")
lineage_tree_4 = lineageot.fit_tree(adata[adata.obs['origin_cell'] == 4], 4)

**Error :** 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/ngheziel/ngheziel/CellLineage/LineageOT/lineageot/core.py", line 48, in fit_tree
    barcode_length = adata.obsm[barcodes_key].shape[1]
  File "/home/ngheziel/.conda/envs/lineageOT/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 113, in __getitem__
    _subset(self.parent_mapping[key], self.subset_idx),
  File "/home/ngheziel/.conda/envs/lineageOT/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'barcodes'

adata.obs : (I renamed myself the index since it was not working)

**>>> adata.obs**

barcodes                             orig.ident  nCount_RNA  nFeature_RNA  ...        day                 x         y                                                 ...                          
AAACCCAAGGCGAACT-1           0           62422.0          7185            ...          0     -10.055300 -0.528188

**>>> session_info.show()**
-----
anndata             0.7.8
lineageot           NA
numpy               1.22.2
session_info        1.0.0
-----
Python 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:28:35) [GCC 9.4.0]
Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2022-02-11 14:37

I do not understund where the error come from, would you mind helping me ? 
The data concern neurons at days 0, 1, 4. The adata.obs.index is barcodes.

Thank you very much for your help, 
Best regards,
Nadine

**Comment by aforr** [comment]
Hi Nadine,

What is the data you're trying to run LineageOT on? 

The barcodes the code is looking for (which leads to the error) are lineage tracing barcodes to construct a lineage tree from, not the barcodes that index cells in adata.obs.index. If your experiment didn't involve lineage tracing, you should be sticking with WOT which only uses expression data.

If you do have lineage tracing data, you'll need to add it to your AnnData object before running LineageOT. How exactly to do that depends on what measurements you have.

**Comment by nadinegheziel** [comment]
Hi @aforr,

You're totally right, I thought it was the barcodes from the single cell experiment
I don't have the lineage tracing data yet, I will work on it now on! 👍 

Sorry for the inconvenience,
And thank you very much for you quick answer 💯 
Nadine
