### ISSUE TITLE
lineageot.fit_lineage_coupling() ValueError

### ISSUE THREAD

**Issue by eblchen** [aforr/LineageOT-demo#3]
Hi, I was just trying to run the plot_clonal_pipeline as a test but came into this error when trying the coupling.
I may be just missing something silly but was wondering if you could help?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 coupling = lineageot.fit_lineage_coupling(adata, t1, t2, lineage_tree_t2)

File [c:\Users\echen\Anaconda3\envs\lineageOT\lib\site-packages\lineageot\core.py:161](file:///C:/Users/echen/Anaconda3/envs/lineageOT/lib/site-packages/lineageot/core.py:161), in fit_lineage_coupling(adata, time_1, time_2, lineage_tree_t2, time_key, state_key, epsilon, normalize_cost, ot_method, marginal_1, marginal_2, balance_reg)
    158     state_arrays['late'] = adata[adata.obs[time_key] == time_2].obsm[state_key]
    160 # annotate tree
--> 161 inf.add_leaf_x(lineage_tree_t2, state_arrays['late'])
    164 # Add inferred ancestor nodes and states
    165 inf.add_nodes_at_time(lineage_tree_t2, time_1)

File [c:\Users\echen\Anaconda3\envs\lineageOT\lib\site-packages\lineageot\inference.py:186](file:///C:/Users/echen/Anaconda3/envs/lineageOT/lib/site-packages/lineageot/inference.py:186), in add_leaf_x(tree, x_array)
    184         tree.nodes[cell]['cell'].x = x_array[cell, :]
    185     else:
--> 186         tree.nodes[cell]['cell'] = sim.Cell(x_array[cell, :], np.nan)
    187 return tree

File [c:\Users\echen\Anaconda3\envs\lineageOT\lib\site-packages\lineageot\simulation.py:87](file:///C:/Users/echen/Anaconda3/envs/lineageOT/lib/site-packages/lineageot/simulation.py:87), in Cell.__init__(self, x, barcode, seed)
     85     self.seed = seed
     86 else:
---> 87     self.seed = np.random.randint(2**32)
     88 return

File mtrand.pyx:763, in numpy.random.mtrand.RandomState.randint()

File _bounded_integers.pyx:1336, in numpy.random._bounded_integers._rand_int32()

ValueError: high is out of bounds for int32

**Comment by aforr** [comment]
Hi Emilia,

What version of numpy are you using? And what operating system? The problem line `np.random.randint(2**32)` assumed the default integers were int64, while you appear to have int32 when the type isn't specified.

I updated the lines where seeds are set to use a smaller range that won't go out of bounds for int32. Could you check whether that resolves your problem?

**Comment by eblchen** [comment]
Hi, thank you that seems to have fixed it!
